services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:2701  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 2701:2701
    depends_on:
      - backend

  backend:
    build:
      context: .    
    environment:
      - FLASK_SERVER_PORT=2701
    volumes:
      - ./:/src
    